include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/generated/**/*.dart
    - lib/generated_plugin_registrant.dart